modLoader="javafml"
loaderVersion="[32,)"
license="CoFH \"Don't Be a Jerk\" License"

[[mods]]
	modId="draconicevolution"
	displayName="Draconic Evolution"
	version="3.0.0"
	authors="brandon3055"
	description=''''''
[[dependencies.draconicevolution]]
	modId="forge"
    mandatory=true
	versionRange="[32,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.draconicevolution]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

